stages:
  - builder
  - build

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build_builder:
  stage: builder
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /root/.docker
    - >
      echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" >
      /kaniko/.docker/config.json
    - >
      /kaniko/executor --cleanup --snapshotMode=redo --context="$CI_PROJECT_DIR"
      --dockerfile="$CI_PROJECT_DIR/Dockerfile.builder"
      --destination=$CI_REGISTRY_IMAGE/builder:latest
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
      changes:
        - Dockerfile.builder

build:
  image:
    name: $CI_REGISTRY_IMAGE/builder:latest
  stage: build
  script:
    - ./gradlew npmInstall build publish

after_script:
  - echo "End CI"